print('Hello my name is "Harsh". I love Coding')
print("This is my first program")

x=input("Enter any number for variable X : ")
y=input("Enter any number for variable Y : ")
z=input("Enter any number for variable Z : ")
x1=type(x)
y1=type(y)
z1=type(z)
print("Value1=",x)
print("Datatype=",x1)
print("Value2=",y)
print("Datatype=",y1)
print("Value3=",z)
print("Datatype=",z1)
